openwisp/openwisp-utils

- openwisp_utils/api/serializers.py
- requirements-test.txt
- tests/test_project/models.py
- tests/test_project/serializers.py
- tests/test_project/tests/test_api.py
Added new file `openwisp_utils/api/serializers.py` and implemented a base serializer that can be used in other projects.
Fixes #12
> BaseSerializer Implemented

- openwisp_utils/ci.py
- requirements-test.txt
- setup.py
- tests/test_project/tests/test_ci.py
> [qa] Added check migration filename script

- .travis.yml
- requirements-test.txt
- setup.py
We will use openwisp-utils in all the other modules to pin down the flake8 and isort versions to reduce the maintenance overhead of having to update the `flake8` and `isort` versions in each OpenWISP 2 module
> [qa] Pin down flake8 and isort in extra_requires['qa']

- .travis.yml
- README.rst
- openwisp_utils/qa.py
- setup.py
- tests/test_project/tests/test_qa.py
Round 2 of #25, I hope the build won't get stuck this time.
@ppabcd see the improvements to your code, especially regarding readability
@atb00ker I found out a few things that needed improvement in the migration check as well, these kind of checks are designed to be used as linux commands so they should not raise exceptions in case of failure but simply print a message and exit with an exit code higher than zero.
I've added some basic docs in the readme and last but not least I've added a way to skip the commit message check (using the `#noqa` keyword in the commit message) in case we encounter some legit case which we didn't plan here and we don't want to block the build, we may remove this option in the future once we are confident all cases are covered.
Related to #20 and #23.
> [qa] Improved our quality assurance checks

- openwisp_utils/qa.py
- setup.py
- tests/test_project/tests/test_qa.py
Google Code-in Task : https://codein.withgoogle.com/dashboard/task-instances/5188396768034816/
Fixes #20
> Added commit message style check

- .travis.yml
This pull request removes reference to deprecated Travis CI `sudo: true`, as per https://config.travis-ci.com/explore.
Google Code-in Link: https://codein.withgoogle.com/dashboard/task-instances/5846031841886208/
This is Code-in user aaPle.
> [ci] Remove deprecated sudo Travis key

- openwisp-utils-qa-checks
This pull request makes `openwisp-utils-qa-checks` run all checks, even if some fail. The exit code's _i_-th bit represents whether corresponding check has failed or not. Here's a table of current checks' errors:
| No. | Name | Raised at |
|-----|--------------------------------------------------------------------------------|-----------------------------|
| 0 | `checkendline` fail | openwisp-utils-qa-checks:50 |
| 1 | `checkmigrations` fail | openwisp-utils-qa-checks:61 |
| 2 | `flake8` fail | openwisp-utils-qa-checks:66 |
| 3 | `isort` fail | openwisp-utils-qa-checks:71 |
| 4 | No `migration-path` provided and `--skip-checkmigrations` option is not chosen | openwisp-utils-qa-checks:58 |
| 5 | `checkcommit` fail | openwisp-utils-qa-checks:80 |
> Common CI script: make all checks even in case of failures

- README.rst
Adds documentation for the [#noqa option](https://github.com/openwisp/openwisp-utils/blob/master/openwisp_utils/qa.py#L76) in the README
Closes #49
> [docs] Add noqa to checkcommit docs

- README.rst
- openwisp-utils-qa-checks
Add support for multiple check migrations by passing the arguments with space delimited string.
Closes #52 
For example:
```
checkmigrations --migrations-to-ignore 3 \
--migration-path ./openwisp_users/migrations/ || exit 1
checkmigrations --migrations-to-ignore 2 \
--migration-path ./tests/testapp/migrations/ || exit 1
```
Can be changed by:
```
openwisp-utils-qa-checks --migration-path "./openwisp_users/migrations/ ./tests/testapp/migrations/" --migrations-to-ignore "3 2"
```
If `MIGRATIONS_TO_IGNORE` were not set, or the length of it's array is less than the length of `MIGRATION_PATH` array, then `MIGRATIONS_TO_IGNORE` will be set to 0 by default.
I also add progress info for each check to make it easier for us to debug later.
> [ci] Add support for multiple check migrations

- README.rst
Adds openwisp-utils-qa-checks to the README file and describes its purpose. It also includes `checkendline`
Fixes #47
> [docs] Documents openwisp-utils-qa-checks #47

- openwisp-utils-qa-checks
When unknown argument is passed to `openwisp-utils-qa-checks` it exits with 0, as if everything is ok. This PR fixes it.
> [enhancement] Make openwisp-utils-qa-checks fail on unknown argument

- .travis.yml
- openwisp_utils/admin.py
- openwisp_utils/staticfiles.py
- requirements-test.txt
- setup.py
- tests/test_project/tests/test_admin.py
- tests/test_project/tests/test_api.py
- tests/test_project/tests/test_qa.py
Dropped python2 support and updated requirements.
Fixes https://github.com/openwisp/openwisp-utils/issues/43
> [requirements] Update dependencies & drop python 2 support

- openwisp-utils-qa-checks
Changed echo to printf in pending migrations check
> [ci] Newline is not interpreted in openwisp-utils-qa-checks #72

- openwisp-utils-qa-checks
Some checks in `openwisp-utils-qa-checks` still have "Running" messages. This PR fixes it.
> [qa] Remove unwanted "Running" messages in openwisp-utils-qa-checks

- README.rst
- openwisp_utils/admin_theme/apps.py
- openwisp_utils/admin_theme/checks.py
- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/settings.py
- openwisp_utils/admin_theme/templates/admin/base_site.html
- tests/settings.py
- tests/test_project/static/custom-admin-theme.css
- tests/test_project/tests/test_admin.py
Added feature to pass custom CSS and JS for admin theme by providing values for  `OPENWISP_ADMIN_THEME_CSS` and `OPENWISP_ADMIN_JS` settings.
Added documentation and tests for the above feature.
P.S: Should be merged after #80 :smile: 
Closes #79
> [admin-theme] Adding custom CSS and JS #79

- README.rst
- openwisp-qa-format
- openwisp-utils-qa-checks
- openwisp_utils/admin.py
- openwisp_utils/admin_theme/admin.py
- openwisp_utils/admin_theme/apps.py
- openwisp_utils/admin_theme/checks.py
- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/settings.py
- openwisp_utils/api/serializers.py
- openwisp_utils/base.py
- openwisp_utils/loaders.py
- openwisp_utils/qa.py
- openwisp_utils/staticfiles.py
- runtests.py
- setup.cfg
- setup.py
- tests/local_settings.example.py
- tests/settings.py
- tests/test_project/admin.py
- tests/test_project/migrations/0001_initial.py
- tests/test_project/migrations/0002_add_key_id_project.py
- tests/test_project/models.py
- tests/test_project/test_api/urls.py
- tests/test_project/test_api/views.py
- tests/test_project/tests/__init__.py
- tests/test_project/tests/test_admin.py
- tests/test_project/tests/test_qa.py
- tests/test_project/tests/test_test_utils.py
- tests/urls.py
This allows us to define a common code formatting standard and avoids
having to manually do these changes manually.
It is enabled by default and can be disabled using --skip-black
This PR also formats the code in this repository using black.
Also added flag --force-checkcommit to force the commit message check
Fixes #86
> [black] Add black support

- openwisp-utils-qa-checks
The line contains backticks, making the script to interpret it as
a command to be run and fail because manage.py is not expected
to be there. See this travis log
Fixes #95
> [checks] Fix crash when pending migrations check fails #95

- openwisp_utils/loaders.py
Used importlib because to use templates from `openwisp_controller.config`, normal `__import__` wasn't working.
> [improvement] Dependency loader importlib

- CHANGES.rst
- openwisp_utils/__init__.py
- [fix] Fix crash when pending migrations check fails
- [add] default_or_test function
- [add] Added deep_merge_dicts function
- [add] formatter: black<=19.10b0
- [add] OPENWISP_API_INFO setting
- [add][api] Require authentication for API docs if DEBUG is False
- [add][api] Implement ScopedRateThrottle by default
- [add][api] Introduced api.ApiAppConfig
- [add][rest] optional swagger API endpoints
- [add][rest] django-filter
- [docs] Re-ordered, added information and improved existing docs
- [update] Added support for flake8 flake8<=3.9
- [change] Renamed test_api to api for consistency
- [change] Rename openwisp-utils-qa-checks to openwisp-qa-check
- [change][api] Renamed /api/v1/swagger/ to /api/v1/docs/
- [improvement] Moved to importlib for Dependency loader & staticfiles for …
> 0.5.0 release

- openwisp_utils/tests.py
- tests/test_project/tests/test_test_utils.py
Closes #124
The actual fix is only one line,
```python
name = name.split('\n')[0]
```
Rest all restructuring was needed for the test, since the bug will show up only for a slow test with a docstring.
> [fix] Add support for docstrings in TimeLoggingTestRunner #124

- README.rst
- openwisp_utils/admin_theme/context_processor.py
- tests/test_project/tests/test_admin.py
Fixed issue by making sure users can access just the models
they are permitted to access.
Fixes #103
Closes #104
> [admin-theme] menu doesn't respect assigned permissions #103

- CHANGES.rst
- openwisp_utils/__init__.py
- [fix] Stopped commit check from being performed on master (after merge)
- [deps] Added support for django 3.1
- [ux/admin-theme] Force z-index on main menu to stay on top
Signed-off-by: Ajay Tripathi <ajay39in@gmail.com>
> 0.6.1 release

- openwisp_utils/qa.py
- tests/test_project/tests/test_qa.py
Added failing test + fix.
Expecting build to fail, I sent a commit message which should trigger the failure on purpose to ensure it works.
> [fix] Fixed commit message check missing close/fix keyword #136

- README.rst
Replaced `python setup.py develop` with `pip install -e .[qa,rest]` for developmet version.
Closes #114
> [docs] Fixed command not installing dependencies in development environment

- README.rst
added documentation for `OPENWISP_ADMIN_SHOW_USERLINKS_BLOCK` settings in README.rst
TASKS DONE:-
closes #100
> [docs] Added documentation for OPENWISP_ADMIN_SHOW_USERLINKS_BLOCK #100

- openwisp_utils/admin.py
- openwisp_utils/qa.py
- openwisp_utils/tests.py
- setup.py
- tests/settings.py
- tests/test_project/admin.py
- tests/test_project/api/urls.py
- tests/test_project/apps.py
- tests/test_project/migrations/0001_initial.py
- tests/test_project/migrations/0002_add_key_id_project.py
- tests/test_project/tests/test_api.py
- tests/test_project/tests/test_qa.py
- tests/test_project/tests/test_test_utils.py
> [fix] Fixed error in ReStructuredText Check #150

- README.rst
- openwisp_utils/storage.py
- setup.py
- tests/test_project/tests/test_storage.py
Ported changes from  storage.py in ansible-openwisp2 to storage.py in openwisp_utils/
Added documentation and written test for `CompressStaticFilesStorage` in openwisp_utils.storage
In documentation created a separate storage utilities section and in settings added `OPENWISP_STATICFILES_VERSIONED_EXCLUDE`.
Created test_storage in tests/test_project/tests , The test creates a temporary folder and 2 text files in it and then runs collectstatic in that folder and checks whether the file hashed is correct or not and later deletes that folder.
Fixes #166
> [feature] Added a Custom Static Storage 

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
When width is lower than 1024px, the user goes down to a new row.
https://user-images.githubusercontent.com/7120526/114606419-862ea580-9c9b-11eb-8717-5becc4aac1cc.mp4
This pull request fixes that
https://user-images.githubusercontent.com/7120526/114606449-8dee4a00-9c9b-11eb-82fd-8dfd91a98bb3.mp4
> [ux] Fix header user on small screens

- CHANGES.rst
- setup.py
I have tested all of this module's with `djangorestframework~=3.12.0`:-
except `openwisp-radius` all of them are compatible, and are passing all the tests, 
it will get fixed by https://github.com/openwisp/openwisp-radius/pull/203/
Closes #164
> [deps] Updated DRF to 3.12 #164

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
The width of the menu toggle button has been changed from 40 to 52px
Before:
After:
> [ux] Menu button toggle 52px width

- openwisp_utils/admin_theme/static/rest_framework/css/browsable-api.css
- openwisp_utils/admin_theme/templates/rest_framework/api.html
django-pipeline strips spaces from pre-formatted text on minifying HTML.
This destroys the representation of data on browsable API views.
Added a workaround to restore presentation to original form using CSS.
Related: https://github.com/openwisp/ansible-openwisp2/issues/256
> [fix] Added workaround for minification of browsable API view

- .stylelintrc.json
Fixing error:
```
openwisp_monitoring/device/static/monitoring/css/leaflet.fullscreen.css
35:19  ✖  Unexpected unit "dpi"   unit-allowed-list
```
> Added stylelint unit `dpi`

- README.rst
- openwisp_utils/admin_theme/dashboard.py
- tests/test_project/apps.py
- tests/test_project/templates/dashboard_test.html
- tests/test_project/tests/test_dashboard.py
- tests/test_project/tests/test_storage.py
I want to pass custom variables like 'base_url_to_monitoring' in my template, currently I can't add the same in the context.
This PR allows me to add any custom variable to the templates. 
Tested in https://github.com/openwisp/openwisp-monitoring/pull/304
> [enhancement] Dashboard extra-config option

- openwisp_utils/api/urls.py
- tests/test_project/api/urls.py
- tests/urls.py
Changed all `url()` calls to either `path()` or `re_path()`
`re_path()` was used when the use of regex was necessary.
fix #155
> #Closes #155#
> [enhancement] Changed url to path/re_path #155

- openwisp_utils/admin_theme/menu.py
###Changes
Changed error message for "another group is already registered at position "X".
closes #227
> [change] Changed another group present message #227

- openwisp_utils/qa.py
- tests/test_project/tests/test_qa.py
Fix commit message check is failing when there is a dot after issue
Closes #187.
> [qa] Fix commit message check fails #187

- openwisp_utils/admin_theme/email.py
- tests/test_project/tests/test_email.py
Added mail.send function in try except block to track the error
Fixes #278
> [Fix] Sending emails to user with invalid email #278

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
- openwisp_utils/admin_theme/static/admin/css/ow-dashboard.css
Fixes #275
Fix charts and login on small screens ( Samsung s8+, IPhone SE etc)
> [fix] Homepage charts and login on small screens #275

- openwisp_utils/admin_theme/static/drf-yasg/ow-drf-yasg.css
- openwisp_utils/admin_theme/static/rest_framework/css/browsable-api.css
- openwisp_utils/admin_theme/templates/drf-yasg/swagger-ui.html
- openwisp_utils/admin_theme/templates/rest_framework/api.html
Closes #197
- Changed API docs theme to look similar to `admin`
https://user-images.githubusercontent.com/56113566/152698653-19670156-ac52-4f53-be05-67bb95d96950.mp4
https://user-images.githubusercontent.com/56113566/153577528-ab644cc6-0daa-4208-92ce-97cb4c157170.mp4
> [feature] API docs theme #197

- openwisp_utils/admin_theme/static/admin/js/menu.js
Closes #235
Removed the cleanUp JS function which removed duplicated objects.
The duplicated objects are not showing up anymore in my env, but we need to double check whether they show up in other configurations and if they do, we need to understand the reason and fix the root cause.
Closes #235.
> [chore] Removed cleanUp JS function from menu.js #235

- requirements-test.txt
Updated test project to use latest version of openwisp-controller. 
Otherwise, netjsonconfig was installing Jinja2 2.x which is incompatible for newer version of MarkupSafe.
> [deps] Updated tests requirements

- openwisp_utils/admin_theme/static/rest_framework/css/browsable-api.css
- Fixed browsable API pagination style
https://user-images.githubusercontent.com/56113566/157889453-272e2ddd-e9d1-4819-99f3-e6b9dee9395a.mp4
Fixes #288
> [fix:ui] Fixed browsable API pagination style #288

- README.rst
- openwisp_utils/admin_theme/dashboard.py
- tests/test_project/tests/test_dashboard.py
Added __exact to the target_link of group_by dashboard
elements, this allows to show the filters in the
target page pre-selected with the chosen value, eg:
When clicking on the applied config status,
not only the page shows all the devices which have
their config applied but also shows the
Configuration Status filter with the "applied"
value already pre-selected (which was not happening
before this change).
> [fix] Fix dashboard details

- README.rst
- openwisp_utils/admin_theme/static/admin/js/ow-dashboard.js
- tests/test_project/apps.py
- tests/test_project/tests/test_dashboard.py
Added "title" field to the quick_link configuration. The "title" is
used to set the "title" attribute of the quick link button.
> [enhancement] Improved the dashboard chart quick link

- README.rst
- openwisp_utils/admin_theme/email.py
- tests/test_project/tests/test_email.py
Closes #311
Allowed passing extra arguments to django send_email function
> [change] Allowed passing extra arguments to django send_email function #311

- README.rst
- openwisp_utils/admin_theme/dashboard.py
Added "organization_field" property to "query_params" of dashboard chart. It allows specifying inderect relation with the Organization model.
> [feature] Added "organization_field" property for dashboard chart query

- openwisp_utils/admin_theme/templates/admin/edit_inline/help_text_stacked.html
The default value for the help text icon included a leading "/". This resulted in "Server 500" with CompressStaticFilesStorage storage backend.
> [fix] Fixed alert icon URL in HelpTextStackedInline template

- openwisp_utils/admin_theme/views.py
- tests/test_project/admin.py
- tests/test_project/tests/test_admin.py
This patch adds basic support for reverse relations to `AutocompleteFilter`, I added a basic test and I did manual testing.
> [feature] Added basic support for reverse relations to AutocompleteFilter

- README.rst
- openwisp_utils/admin_theme/admin.py
- openwisp_utils/admin_theme/settings.py
- openwisp_utils/admin_theme/templates/admin/auto_filter.html
- openwisp_utils/admin_theme/views.py
- tests/test_project/admin.py
- tests/test_project/tests/test_admin.py
- tests/test_project/tests/test_selenium.py
[[fix] Fixed "None" option of AutocompleteFilter](https://github.com/openwisp/openwisp-utils/commit/1cb7e4c52b9bf379346e9b647085d1acc5cdb8cd) 
AutocompleteFilter shows "None" option only if the field is
nullable. 
----
[[feature] Added setting to make AutocompleteFilter view configurable](https://github.com/openwisp/openwisp-utils/commit/caecb465db64988bd3834168b5d14e149ff1c94a) 
Added "OPENWISP_AUTOCOMPLETE_FILTER_VIEW" project setting to allow
configuring the view.
---
**Required by**
> [fix/feature] Fix autocomplete filter

- openwisp_utils/storage.py
- setup.py
Removed the workaround for DRF-yasg as described in #306 .
> Removed the following workaround added in static file storage
[openwisp-utils/openwisp_utils/storage.py](https://github.com/openwisp/openwisp-utils/blob/afa8f7bfa7a4532aab7c1c4fa4d76e55eea635c7/openwisp_utils/storage.py#L10-L23)
> #Closes #306 #
> [chores] Upgrade drf-yasg~=1.21.0 #306

- openwisp_utils/admin_theme/filters.py
- tests/test_project/tests/test_admin.py
It would be good to send this fix upstream but it seems that the package we depend on is not really active in maintaining it so let's fix it here for now and in the future we'll look for a better solution or fork the package to maintain it on our own.
> [fix] Fixed autocomplete filter exception on invalid input #326

- README.rst
- openwisp_utils/db/backends/spatialite/base.py
"openwisp_utils.db.backends.spatialite" extends
"django.contrib.gis.db.backends.spatialite" to implement workaround for https://code.djangoproject.com/ticket/32935.
> [feature] Added "openwisp_utils.db.backends.spatialite" database backend

- openwisp_utils/admin_theme/dashboard.py
- tests/test_project/apps.py
- tests/test_project/tests/test_dashboard.py
Make sure to HTML escape all dashboard labels.
> [fix] Make sure to HTML escape all dashboard labels

- openwisp-qa-check
Closes #163
>Updated the script to check commit messages to work with GitHub Actions.
>Used the GITHUB_ACTIONS and GITHUB_EVENT_NAME environment variables to determine if the script is running in a GitHub >Actions workflow triggered by a pull request.
Skipped the commit message check if the workflow is triggered by a pull request.
> #Closes #163 #
> [qa] Commit check now work on github actions #163

- README.rst
- openwisp_utils/utils.py
- setup.py
- we need to ensure a recent version of requests is installed
- docs had several mistakes
- some code was repeated twice in the function definition
> [fix] Fixed several minor issues in retryable requests

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
> [chores] Added CSS for inline-link-container

- openwisp_utils/tests.py
> [chores:tests] Added AdminActionPermTestMixin

- docs/developer/admin-utilities.rst
- openwisp_utils/admin_theme/templates/admin/submit_line.html
> [change] Made admin/submit_line.html extendable

- setup.py
djangorestframework>=3.15.2 dropped support for Django 3.2.
> [deps] Bumped djangorestframework>=3.14,<3.15.2

- .github/workflows/pypi.yml
- openwisp_utils/metric_collection/migrations/0001_initial.py
- setup.cfg
- setup.py
- tests/openwisp2/settings.py
Added workflow for publishing PyPI packages
> [ci] Added workflow for publishing PyPI packages

- .github/workflows/reusable-version-branch.yml
- .github/workflows/version-branch.yml
- CHANGES.rst
- docs/developer/index.rst
- docs/developer/reusable-workflows.rst
- openwisp_utils/__init__.py
> [ci] Added GitHub workflow to replicate commits to version branch

- openwisp-qa-check
Please [open a new issue](https://github.com/openwisp/openwisp-utils/issues/new/choose) if there isn't an existing issue yet.
> [fix] Change docs url in openwisp-qa-check

- setup.py
The `coveralls` Python package is no longer actively maintained and is not needed locally.
Coverage reports are not uploaded to Coveralls from local builds. On CI, the `coverallsapp/github-action@v2` GitHub Action handles uploading coverage reports to coveralls.io in CI.
The coveralls package does not support Python 3.13 which is required for #452
> [deps] Remove coveralls in favor of coverage

- .github/workflows/ci.yml
- docs/developer/other-utilities.rst
- openwisp_utils/admin_theme/static/admin/css/openwisp.css
- openwisp_utils/admin_theme/templates/admin/base_site.html
- openwisp_utils/tests/selenium.py
- tests/openwisp2/settings.py
- tests/test_project/tests/test_selenium.py
- tests/test_project/tests/test_storage.py
- tests/test_project/tests/utils.py
Closes #439
- Added support for Python 3.11, 3.12 and 3.13
- Dropped support for Django 3.2
- Dropped support for Python 3.8
**CSS changes related to changes in the Django admin:**
- Added border to the inline admin heading (I removed them in OpenWISP)
- Changed HTML elements for FilteredMultiSelect widget (widget for adding group/permission to the user)
- Added a button for resetting password of the user
---
**Blockers**
> [deps] Added support for Django 5.x #439

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
On Django 5.2, the object tools on change page were overlapping with the filters.
> [fix] Django 5.2: Updated CSS to prevent overlapping of object tools with filters

- docs/developer/test-utilities.rst
- openwisp_utils/tests/selenium.py
- tests/test_project/tests/test_selenium.py
Closes #464
Retry selenium tests if the tests fails on the first attempt. This prevents failng the CI build from flaky tests.
> [feature] Added retry mechanism to SeleniumTestMixin #464

- openwisp_utils/admin_theme/system_info.py
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
Migrated `pkg_resources` (deprecated) to `importlib` in system_info.py.
> [chores] Migrated pkg_resources (deprecated) to importlib in system_info.py

- openwisp_utils/admin_theme/templates/openwisp_utils/email_template.html
Bug:
Setting both heights and width would require overriding the template when the logo is customized.
Fix:
Setting the height to auto let's the logo adapt to width. If further customizations are required, then the user will need to override the email template.
> [fix] Fixed the height of the logo in email template
