- .travis.yml
- runcheckmigration
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/4526382303412224/
> [qa] add ci check for migrations

- runcheckendline
I have created an alternative implementation what Reza already did.
I'm sorry that I couldn't make it in GCI. I tried to make it cleaner
and also written a script to add newlines at the end, which is available at : https://github.com/unsuitable001/usnippet/blob/master/addendline.sh
Closes #37 
Fixes #29
> [qa] Added a check for empty line at the end of a file #29

- README.rst
- openwisp_utils/admin_theme/admin.py
- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/settings.py
- openwisp_utils/admin_theme/site.py
- tests/settings.py
- tests/test_project/admin.py
- tests/test_project/site.py
- tests/test_project/templates/password_change_done.html
- tests/test_project/tests/test_admin.py
- tests/urls.py
> [enhancement] Overrided django.contrib.admin.AdminSite #42

- .travis.yml
- README.rst
- openwisp_utils/admin_theme/static/admin/css/openwisp.css
Will require dependencies to use django >= 2.2
> [theme] Adapted menu to django 2.2

- openwisp-utils-qa-checks
Add check for Make Migrations
Closes #53
> [ci] add check for pending migrations #53

- openwisp_utils/admin_theme/context_processor.py
Added support for `admin_site` in `context_processor.py`
> [feature] Added support for admin_site

- README.rst
- openwisp_utils/admin_theme/__init__.py
- openwisp_utils/admin_theme/admin.py
- openwisp_utils/admin_theme/apps.py
- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/settings.py
- openwisp_utils/admin_theme/site.py
- tests/test_project/admin.py
- tests/test_project/templates/password_change_done.html
- tests/urls.py
Simplifies the implementation of OPENWISP_ADMIN_SITE_CLASS
in order to avoid having to change all the openwisp modules.
Meaningless work saved.
> [admin] Improved custom admin site implementation #42

- openwisp_utils/admin_theme/admin.py
- tests/test_project/admin.py
- tests/test_project/apps.py
- tests/test_project/tests/test_admin.py
- tests/test_project/tests/test_qa.py
Fixes #57
**Depends on: https://github.com/openwisp/openwisp-utils/pull/62**
> [tests] Increased text coverage to 100% #57

- .travis.yml
- setup.py
Added support for Django 3.0, dropped support for Django 1.11
**Blocked by: https://github.com/openwisp/openwisp-utils/pull/44**
> [enhancement] Added support for Django 3.0

- openwisp_utils/qa.py
Allow release commits in commit check
Fixes #75
> [qa] Commit check, allow release commits #75

- CHANGES.rst
- openwisp_utils/__init__.py
Signed-off-by: Ajay Tripathi <ajay39in@gmail.com>
> 0.4.2 release

- README.rst
> [docs] Fixed content mismatch in adding Dependency Loader #80

- openwisp_utils/base.py
> [KeyField] Allow overrding default and validators #83

- README.rst
- openwisp_utils/admin_theme/apps.py
- openwisp_utils/admin_theme/checks.py
- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/settings.py
- openwisp_utils/admin_theme/templates/admin/base_site.html
- tests/settings.py
- tests/test_project/static/custom-admin-theme.css
- tests/test_project/tests/test_admin.py
> [admin-theme] OPENWISP_ADMIN_THEME_CSS > OPENWISP_ADMIN_THEME_LINKS

- README.rst
- openwisp_utils/tests.py
- tests/test_project/tests/test_test_utils.py
> [enhancement] Add catch_signal test utility

- .travis.yml
- requirements-test.txt
- setup.py
> [qa] Require coveralls (depends on coverage)

- openwisp-utils-qa-checks
Previously this check was only run in Pull Requests.
Now it is possible to force it by using --force-checkcommit
Partially fixes #86
> [checkcommit] Add argument to force message commit check #86

- openwisp-utils-qa-checks
This check is run when any of the following conditions is true:
1. --force-checkcommit is specified
2. This function is invoked from Travis building a Pull Request
Context: https://github.com/openwisp/openwisp-utils/pull/90#issuecomment-609922762
Related to #86
> [checkcommit] Fix logic for --skip-checkcommit and --force-checkcommit #86

- .travis.yml
- README.rst
- openwisp_utils/api/urls.py
- openwisp_utils/settings.py
- setup.py
- tests/settings.py
- tests/urls.py
> [rest] Add optional swagger API endpoints #102

- openwisp_utils/utils.py
- tests/test_project/tests/test_test_utils.py
See https://github.com/openwisp/openwisp-notifications/pull/19#discussion_r428313884
> [utils] Added deep_merge_dicts

- openwisp-qa-check
Closes #127 
P.S: This PR made me realize some cleanup is required in this repository, will do that tomorrow! :smile:
> [minor/fix] Running commitcheck issue #127

- openwisp-qa-check
- working on workbench
- working on PR: https://travis-ci.org/github/atb00ker/openwisp-utils/jobs/718329918
- skipping on master: https://travis-ci.org/github/atb00ker/openwisp-utils/jobs/718330016
> [fix] Fix commit check on travis

- .travis.yml
Use Travis buddy in notifications webhooks to get post build failure summary
from travis.
Closes #109
> [qa] Post build failure summary #109

- README.rst
- openwisp-qa-check
- openwisp_utils/qa.py
- setup.py
- tests/test_project/tests/test_qa.py
Added ReStructuredText checks to openwisp-qa-check
Will check recursively for errors in reStructuredText
Closes #144
> [qa] Added RestructuredText checks #144

- openwisp_utils/qa.py
- setup.py
Fixed issue with checkrst when sphinx directives are included.
Fixes #147
> [fix] Fixed issue with ReStructeredText checks #147

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
> [Fix] Fixed shifting of html due to main-menu #153

- README.rst
- openwisp_utils/utils.py
- tests/settings.py
- tests/test_project/apps.py
> [menu] Add way to register menu items #106

- README.rst
- openwisp_utils/tests.py
- tests/test_project/tests/test_qa.py
- tests/test_project/tests/test_test_utils.py
> [test] Test Utility to redirect noisy output #98

- openwisp_utils/qa.py
- tests/test_project/tests/test_qa.py
> [change] Skip commit check on commits prefixed with "Bump" #159

- openwisp_utils/qa.py
- tests/test_project/tests/test_qa.py
> [qa] Fixed failing commit checks for co-authored commits #167

- .github/workflows/ci.yml
Fixed CI
relate to https://github.com/openwisp/openwisp-controller/issues/417
> [ci] Fixed CI for different versions of django

- CHANGES.rst
- openwisp_utils/__init__.py
- openwisp_utils/qa.py
- tests/test_project/tests/test_qa.py
> 0.7.4 release

- CHANGES.rst
- openwisp_utils/__init__.py
- openwisp_utils/admin_theme/static/rest_framework/css/browsable-api.css
- openwisp_utils/admin_theme/templates/rest_framework/api.html
> 0.7.5 release

- .github/pull_request_template.md
- Added GitHub PR Template for this repository
> [chores] Added GitHub PR Template

- README.rst
- openwisp_utils/tests.py
- tests/test_project/tests/test_test_utils.py
> [feature] Added AssertNumQueriesSubTestMixin #207

- README.rst
> [docs] Fixed typo in readme

- .github/pull_request_template.md
Added rules in PR template checklist
> Added rules in PR template checklist

- README.rst
> [refactor] Minor improvements in openwisp-qa-check docs

- openwisp_utils/admin_theme/menu.py
- tests/test_project/tests/test_menu.py
Raising self-explaining the ``ReserveNotFound`` error so that anyone could find from where this error is coming.
closes #217
> [fix] Raise error when invalid name in config #217

- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/menu.py
> [fix] Removed use of has_permission() #228

- setup.py
We forgot to add this when adding the dashboard feature.
> [fix] Added swapper to requirements

- openwisp_utils/admin_theme/static/admin/css/ow-filters.css
- openwisp_utils/admin_theme/static/admin/js/ow-filter.js
- openwisp_utils/admin_theme/templates/admin/filter.html
Due to different use of different HTML code for filters when number of filters <=4 and >4 was causing issues in other modules. So changed the implementation.
> [change] Use same html for filter

- openwisp_utils/admin_theme/templates/admin/change_list.html
Changed condition for loading of ``filter.js``.
closes #238
> [fix] Fixed filter not working in openwisp-firmware-upgrader #238

- README.rst
- openwisp_utils/admin_theme/menu.py
- tests/test_project/apps.py
- tests/test_project/tests/test_menu.py
Now we can register an item in a registered group.
Tests are also included.
closes #230
> [enhancement] Implemented register_menu_subitem #230

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
I found css used for ``object-tools`` is enough when buttons are used so added some more changes
> [chores] Added css for object-tool button

- openwisp_utils/admin_theme/menu.py
- openwisp_utils/admin_theme/static/admin/css/openwisp.css
- openwisp_utils/admin_theme/static/admin/css/ow-filters.css
- openwisp_utils/admin_theme/static/admin/js/menu.js
- openwisp_utils/admin_theme/static/admin/js/ow-filter.js
- openwisp_utils/admin_theme/templates/admin/base_site.html
- openwisp_utils/admin_theme/templates/admin/change_list.html
- openwisp_utils/admin_theme/templates/admin/filter.html
- openwisp_utils/admin_theme/templates/admin/menu.html
- openwisp_utils/admin_theme/templatetags/ow_tags.py
Improved accessibility of the main menu and filters
closes #215
> [enhancement] Improved-performance-and-accessibility #215

- README.rst
> [docs] Improved consistency of menu function description #244

- openwisp_utils/storage.py
- setup.py
- tests/test_project/apps.py
- tests/test_project/tests/test_selenium.py
- tests/test_project/tests/test_test_utils.py
> [deps] Bumped black version to 21.10b0

- openwisp_utils/admin_theme/apps.py
- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/templates/admin/base_site.html
- tests/settings.py
- tests/test_project/static/dummy.js
- tests/test_project/tests/test_admin.py
Minified files were not used in templates as the url is passed directly to `href` without processing. This PR fixes that.
Closes #237
> [fix] Fix admin_theme links not getting compressed #237

- setup.py
djangorestframework~=3.13.0 fully supports Django 4.0
> [deps] Upgrade djangorestframework~=3.13.0

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
- openwisp_utils/admin_theme/templates/admin/base.html
- Added style variables to prevent color changes in dark mode
Closes #272
> [enhancement] Added body color explicitly #272

- setup.py
Needed to fix https://github.com/psf/black/issues/2964.
> [fix] Updated black to ~=22.3.0

- README.rst
- openwisp_utils/admin_theme/dashboard.py
- openwisp_utils/admin_theme/templates/admin/index.html
- tests/test_project/tests/test_dashboard.py
- tests/test_project/tests/utils.py
Added option to add dashboard templates after chart
> [feature] Added option to add dashboard templates after charts

- openwisp_utils/admin_theme/static/admin/js/ow-dashboard.js
- tests/test_project/tests/test_selenium.py
Fixes #301
--------------------------------
> [fix] Fixed dashboard pie charts not showing 0 for no data #301

- CHANGES.rst
Added changelog for 1.0.2 release
> [docs] Added changelog for 1.0.2 release

- README.rst
- openwisp_utils/__init__.py
- openwisp_utils/admin_theme/filters.py
- openwisp_utils/admin_theme/static/admin/css/ow-auto-filter.css
- openwisp_utils/admin_theme/static/admin/js/ow-auto-filter.js
- openwisp_utils/admin_theme/templates/admin/auto_filter.html
- setup.py
- tests/settings.py
- tests/test_project/admin.py
- tests/test_project/tests/test_selenium.py
Added `AutocompleteFilter` in openwisp admin theme
Closes #298
> [Feature] Added autocomplete filter #298

- CHANGES.rst
(cherry picked from commit fb217ec17f389d95db0cc04863f85a2e06677686)
> [docs] Added changelog for 1.0.4

- openwisp_utils/admin_theme/templates/admin/edit_inline/help_text_stacked.html
- tests/test_project/tests/test_admin.py
> [fix] Fixed `help_text_stacked` not called static #300

- README.rst
- openwisp_utils/admin_theme/apps.py
- openwisp_utils/admin_theme/context_processor.py
- openwisp_utils/admin_theme/theme.py
- tests/test_project/tests/test_admin.py
- tests/test_project/tests/test_theme.py
> [feature] Added functions to register-unregister admin theme #274

- openwisp_utils/admin_theme/filters.py
- openwisp_utils/admin_theme/static/admin/css/ow-auto-filter.css
- openwisp_utils/admin_theme/static/admin/js/ow-auto-filter.js
- openwisp_utils/admin_theme/views.py
- tests/test_project/tests/test_selenium.py
> [enhancement] Added hooks to AutocompleteJsonView

- requirements-test.txt
- tests/test_project/tests/test_selenium.py
- tests/test_project/tests/utils.py
Similar to: https://github.com/openwisp/openwisp-network-topology/pull/187
> [deps] Upgraded selenium

- .github/workflows/ci.yml
- README.rst
- openwisp_utils/test_selenium_mixins.py
- requirements-test.txt
- setup.py
- tests/test_project/tests/utils.py
> [feature] Added SeleniumTestMixin

- .github/workflows/ci.yml
- openwisp_utils/admin_theme/__init__.py
- openwisp_utils/test_selenium_mixins.py
- setup.py
- tests/test_project/__init__.py
- tests/test_project/apps.py
- Dropped support for Django 4.0
- Bumped django-model-utils~=4.3.1
- Bumped djangorestframework~=3.14.0
- Bumped django-filter~=23.2
- Bumped celery~=5.3.0
- Bumped selenium~=4.10.0
Closes #337
> [deps] Added support for Django 4.1 and Django 4.2 #337

- openwisp_utils/test_selenium_mixins.py
> [chores] Randomize remote-debugging-port for Selenium tests #340

- .github/workflows/ci.yml
- openwisp_utils/admin_theme/static/admin/css/openwisp.css
- setup.py
[[deps] Dropped support for Python 3.7](https://github.com/openwisp/openwisp-utils/pull/346/commits/2fb91cfcc52f71c42937b38e174a46450afb1c29)
> [chores] Fixed openwisp.css formatting

- setup.py
> [deps] Updated drf-yasg~=1.21.7 #352

- CONTRIBUTING.rst
- The earlier guideline was not clear , it was just directing to the readme, it was difficult to excatly find the contribution guideline.
- added the the specific link so it is easy to navigate.
> [docs]added the proper instruction guide for the contribution

- openwisp_utils/admin_theme/apps.py
> [fix] Fixed menu URL for system info #237

- README.rst
> [docs] Fixed errors in README

- openwisp_utils/measurements/tasks.py
- openwisp_utils/measurements/tests/runner.py
- openwisp_utils/measurements/tests/test_models.py
> [fix] Fixed mocking of request library in MockRequestPostRunner

- setup.py
The request dependency wasn't automatically updating urllib3.
> [change] Swapped requests with urllib3

- .coveragerc
- .github/workflows/ci.yml
I have added the `tblib` to the QA dependencies, we will need this when tests in the CI fail to see the traceback properly.
> [ci] Run tests in parallel

- .coveragerc
- .github/workflows/ci.yml
> [ci] Minor updates for CI

- tests/test_project/tests/test_selenium.py
Fixed flaky selenium test: test_addition_of_transition_effect.
> [tests] Fixed flaky selenium test: test_addition_of_transition_effect

- .github/workflows/ci.yml
Cache pip deps on Github Actions to speed up builds.
> [ci] Cache pip deps

- openwisp_utils/admin_theme/static/admin/js/menu.js
- openwisp_utils/test_selenium_mixins.py
- tests/test_project/tests/test_selenium.py
Firefox seems to yield more consistent results, while with Chromium we get failures in the CI builds that we can't replicate locally.
> [ci] Switch to Firefox

- docs/developer/admin-theme.rst
- openwisp_utils/admin_theme/email.py
- openwisp_utils/admin_theme/templates/openwisp_utils/email_template.html
> [feature] Made HTML template configurable in send_email

- openwisp_utils/test_selenium_mixins.py
- tests/openwisp2/settings.py
- N/A/ I have updated the documentation.
Control SELENIUM_HEADLESS via env var.
Added:
- `find_element`
- `wait_for_visibility`
- `wait_for_invisibility`
- `wait_for`
These methods will allow us to write tests using best practices more easily.
> [tests] Selenium tweaks: control headless and add useful methods for repetitive actions.

- openwisp_utils/test_selenium_mixins.py
- tests/test_project/tests/test_selenium.py
Added wait_for_presence, updated tests to use helpers.
> [tests] Added wait_for_presence, updated tests to use helpers

- .github/workflows/ci.yml
- openwisp_utils/test_selenium_mixins.py
- CI: Cache APT + Disable man page auto update
- Selenium: increased timeout and disabled hw acceleration
> [ci/selenium] Cache APT, Disable man page auto update, increased timeout and disabled hw acceleration

- .github/actions/retry-command/action.yml
- docs/developer/index.rst
- docs/developer/reusable-github-utils.rst
- openwisp_utils/tests/selenium.py
> [tests] Improved chromedriver options for selenium tests

- setup.py
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
Closes #388
> [deps] Added "channels" and "channels-test" extra requires #388

- openwisp_utils/admin_theme/static/admin/css/openwisp.css
> [fix] Django 5.2: Updated CSS to fix styling of inline headings

- openwisp_utils/admin_theme/static/admin/css/openwisp-info.css
- openwisp_utils/admin_theme/templates/admin/change_list.html
- openwisp_utils/admin_theme/templates/admin/openwisp_info.html
- openwisp_utils/metric_collection/helper.py
- openwisp_utils/metric_collection/migrations/0001_initial.py
- openwisp_utils/metric_collection/models.py
- openwisp_utils/metric_collection/tests/test_consent.py
- Avoid the red color for the "Apply filters" button.
- Improved the metric collection consent UI.
> [chores:ui] Minor improvements to UI

- openwisp_utils/admin_theme/templates/openwisp_utils/email_template.html
- Removed margin-top on logo container
> [fix] Fixed padding of the email container

- setup.py
Upgraded channels[daphne] to ~=4.3.0.
> [deps] Upgraded channels[daphne] to ~=4.3.0

- docs/user/metric-collection.rst
- openwisp_utils/metric_collection/apps.py
- openwisp_utils/metric_collection/helper.py
- openwisp_utils/metric_collection/models.py
- openwisp_utils/metric_collection/tests/__init__.py
- openwisp_utils/metric_collection/tests/test_consent.py
- openwisp_utils/metric_collection/tests/test_models.py
> [feature] Collect metric on opt-out #488

- .github/workflows/ci.yml
- docs/developer/installation.rst
- runtests
- tests/openwisp2/settings.py
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
Let's make sure the instructions for running tests are up to date and easy to use.
> [tests] Added runtests script, updated docs

- setup.py
> [deps] Bumped djangorestframework~=3.16.0

- setup.py
Updated QA dependencies.
Closes #433.
> [deps] Updated QA dependencies
